### ISSUE TITLE
[UPDATE] Renvoyer l'avatar sur les users Github

### ISSUE THREAD

**Issue by LTiollier** [web-id-fr/octools-client#11]
Ajouter `avatarUrl` au User Github

**Comment by charley-webid** [comment]
@LTiollier @cedric-webid Je comprends pas du tout ce ticket donc je vous laisse faire la QA. À priori la PR associée est mergée donc ça doit être en préprod

**Comment by cedric-webid** [comment]
Pareil, je laisse @LTiollier intervenir.
